services:
  angularapp:
    build: angularapp
    ports:
      - "4200:80"
    environment:
    - TZ=Europe/Helsinki
  webapi:
    build: webapi
    ports:
      - "5195:80"
    environment:
    - TZ=Europe/Helsinki